In [21]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import f_classif,chi2,mutual_info_classif

from sklearn.model_selection import train_test_split

ImportError: cannot import name 'f_classif' from 'sklearn.model_selection' (c:\Users\ahmed rodwan\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\__init__.py)

In [4]:
df=pd.read_csv("titanic.csv")

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [8]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [9]:
df['Age']=df['Age'].fillna(df['Age'].median())

In [10]:
df['Embarked']=df['Embarked'].fillna(df['Embarked'].mode()[0])

In [11]:
df['Cabin']=df['Cabin'].fillna("No Cabin")

In [12]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [13]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,No Cabin,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,No Cabin,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,No Cabin,S

In [14]:
encoder=LabelEncoder()
df['Gender']=encoder.fit_transform(df['Sex'])

In [15]:
df.drop(['PassengerId','Name','Ticket','Sex'],axis=1,inplace=True)

In [16]:
df.head()

   Survived  Pclass   Age  SibSp  Parch     Fare     Cabin Embarked  Gender
0         0       3  22.0      1      0   7.2500  No Cabin        S       1
1         1       1  38.0      1      0  71.2833       C85        C       0
2         1       3  26.0      0      0   7.9250  No Cabin        S       0
3         1       1  35.0      1      0  53.1000      C123        S       0
4         0       3  35.0      0      0   8.0500  No Cabin        S       1

In [17]:
df=pd.get_dummies(df,columns=['Embarked'],drop_first=True)
df.head()

,Survived,Pclass,Age,SibSp,Parch,Fare,Cabin,Gender,Embarked_Q,Embarked_S
0,0,3,22.0,1,0,7.2500,No Cabin,1,False,True
1,1,1,38.0,1,0,71.2833,C85,0,False,False
2,1,3,26.0,0,0,7.9250,No Cabin,0,False,True
3,1,1,35.0,1,0,53.1000,C123,0,False,True
4,0,3,35.0,0,0,8.0500,No Cabin,1,False,True

In [18]:
df['Cabin'].value_counts()

Cabin
No Cabin       687
G6               4
C23 C25 C27      4
B96 B98          4
F33              3
              ...
E17              1
A24              1
C50              1
B42              1
C148             1
Name: count, Length: 148, dtype: int64

In [19]:
df['Cabin'] = df['Cabin'].apply(
    lambda x: 'Cabin' if x != 'No Cabin' else 'No Cabin'
)

In [20]:
df.head()

,Survived,Pclass,Age,SibSp,Parch,Fare,Cabin,Gender,Embarked_Q,Embarked_S
0,0,3,22.0,1,0,7.2500,No Cabin,1,False,True
1,1,1,38.0,1,0,71.2833,Cabin,0,False,False
2,1,3,26.0,0,0,7.9250,No Cabin,0,False,True
3,1,1,35.0,1,0,53.1000,Cabin,0,False,True
4,0,3,35.0,0,0,8.0500,No Cabin,1,False,True

In [23]:
df['Cabin']=encoder.fit_transform(df['Cabin'])